[workspace]
resolver = "2"
members = [
    "utils",
    "days/*",
]

[workspace.dependencies]
utils = { path = "utils" }
itertools = "0.13.0"
regex = "1.10.0"
anyhow = "1.0"
thiserror = "1.0"
nom = "7.1"
glam = "0.27"
rayon = "1.10"
criterion = "0.5"
divan = "0.1"